# Generated by Django 4.1.5 on 2023-01-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_alter_airplane_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('login', models.CharField(max_length=50, null=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['name'],
            },
        ),
    ]
